# 2.Multi-Linear Regression

Multiple linear regression (MLR), also known simply as multiple regression, is a statistical technique that uses several explanatory variables to predict the outcome of a response variable. The goal of multiple linear regression is to model the linear relationship between the explanatory (independent) variables and response (dependent) variables. In essence, multiple regression is the extension of ordinary least-squares (OLS) regression because it involves more than one explanatory variable.

In [2]:
import pandas as pd
import numpy as np

In [3]:
train_data=pd.DataFrame({'diameter':[6,8,10,14,18],'toppings':[2,1,0,2,0],'price':[7,9,13,17.5,18]})
train_data

diameter  toppings  price
0         6         2    7.0
1         8         1    9.0
2        10         0   13.0
3        14         2   17.5
4        18         0   18.0

In this DataFrame, the diameter and the toppings are the independent value(x1,x2), because both are independent values by price and price(y) is dependent value to diameter(x1) and toppings(x2)

In [4]:
x_train=train_data[['diameter','toppings']].values   #already reshaped
x_train

array([[ 6,  2],
       [ 8,  1],
       [10,  0],
       [14,  2],
       [18,  0]], dtype=int64)

In [5]:
y_train=train_data[['price']].values   #already reshaped
y_train

array([[ 7. ],
       [ 9. ],
       [13. ],
       [17.5],
       [18. ]])

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
model=LinearRegression()

In [8]:
model.fit(x_train,y_train)

LinearRegression()

In [9]:
test_data = pd.DataFrame({'diameter':[8,9,11,16,12],'toppings':[2,0,2,2,0],'price':[11,8.5,15,18,11]})
test_data

diameter  toppings  price
0         8         2   11.0
1         9         0    8.5
2        11         2   15.0
3        16         2   18.0
4        12         0   11.0

In [10]:
x_test=test_data[['diameter','toppings']].values
x_test

array([[ 8,  2],
       [ 9,  0],
       [11,  2],
       [16,  2],
       [12,  0]], dtype=int64)

In [11]:
y_test=test_data[['price']].values
y_test

array([[11. ],
       [ 8.5],
       [15. ],
       [18. ],
       [11. ]])

The model is only predicted the values by the test-indepndent data

In [12]:
predictions=model.predict(x_test)
predictions

array([[10.0625    ],
       [10.28125   ],
       [13.09375   ],
       [18.14583333],
       [13.3125    ]])

Here, y_test is a targetd value of price or dependent value and prediction is the value obtained by model

In [13]:
for i, prediction in enumerate(predictions):
    print('Predicted value: %s   and   Price: %s' %(prediction,y_test[i]))

Predicted value: [10.0625]   and   Price: [11.]
Predicted value: [10.28125]   and   Price: [8.5]
Predicted value: [13.09375]   and   Price: [15.]
Predicted value: [18.14583333]   and   Price: [18.]
Predicted value: [13.3125]   and   Price: [11.]


# R-Score Value

In [14]:
model.score(x_test,y_test)

0.7701677731318468