# Booston House Price Data Classification

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import cross_val_predict,cross_val_score

In [2]:
bosten_data=load_boston()

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

In [3]:
bosten_data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [4]:
x=bosten_data.data
y=bosten_data.target

In [5]:
bosten_data=pd.read_csv(r'C:\Users\User\anaconda3\Lib\site-packages\sklearn\datasets\data\boston_house_prices.csv')
bosten_data.head()

506  13 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
0     CRIM  ZN      INDUS       CHAS        NOX         RM        AGE   
1  0.00632  18       2.31          0      0.538      6.575       65.2   
2  0.02731   0       7.07          0      0.469      6.421       78.9   
3  0.02729   0       7.07          0      0.469      7.185       61.1   
4  0.03237   0       2.18          0      0.458      6.998       45.8   

  Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  \
0        DIS        RAD        TAX     PTRATIO           B       LSTAT   
1       4.09          1        296        15.3       396.9        4.98   
2     4.9671          2        242        17.8       396.9        9.14   
3     4.9671          2        242        17.8      392.83        4.03   
4     6.0622          3        222        18.7      394.63        2.94   

  Unnamed: 13  
0        MEDV  
1          24  
2        21.6  
3        34.7  
4        33.4

Header change the columns to index 0

In [6]:
bosten_data=pd.read_csv(r'C:\Users\User\anaconda3\Lib\site-packages\sklearn\datasets\data\boston_house_prices.csv',header=1)  
bosten_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [8]:
x_train

array([[3.83684e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.50650e+02, 1.41900e+01],
       [3.61500e-02, 8.00000e+01, 4.95000e+00, ..., 1.92000e+01,
        3.96900e+02, 4.70000e+00],
       [1.31100e-02, 9.00000e+01, 1.22000e+00, ..., 1.79000e+01,
        3.95930e+02, 4.81000e+00],
       ...,
       [5.11358e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        2.60000e+00, 1.01100e+01],
       [5.78900e-02, 1.25000e+01, 6.07000e+00, ..., 1.89000e+01,
        3.96210e+02, 8.10000e+00],
       [1.84982e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 3.79700e+01]])

In [9]:
x_test

array([[3.42700e-02, 0.00000e+00, 5.19000e+00, ..., 2.02000e+01,
        3.96900e+02, 9.80000e+00],
       [9.16400e-02, 0.00000e+00, 1.08100e+01, ..., 1.92000e+01,
        3.90910e+02, 5.52000e+00],
       [5.50070e-01, 2.00000e+01, 3.97000e+00, ..., 1.30000e+01,
        3.87890e+02, 8.10000e+00],
       ...,
       [8.52040e-01, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.92530e+02, 1.38300e+01],
       [1.39134e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        1.00630e+02, 1.51700e+01],
       [9.59571e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.76110e+02, 2.03100e+01]])

In [10]:
y_train

array([19.9, 27.9, 35.4, 22.9, 18. , 15.1, 18.7, 17.7, 13.8, 13.4,  8.5,
       17.6, 24.1, 21.4, 29.1, 18.9, 31.6, 50. , 22.5, 26.7, 50. , 13.9,
       10.2, 11.8, 22.6, 22.4, 18.4, 34.6, 50. , 22.5, 17.9, 14.9, 23.9,
       33.4, 20. , 20.9, 22.2, 48.8, 19.6, 18.5, 48.3, 14.2, 31.5,  5. ,
       10.2, 29.6, 22.6, 14.1, 19. , 13.4, 15. , 23.5, 13.3, 25. , 16.3,
       31. , 25. , 18.4, 24.4, 16.2, 32. , 13.6, 20.6, 17.5, 24.5, 22. ,
       27.5, 19.7, 37.3, 22.6, 15.4, 21.6,  9.7, 19.9, 21.4, 50. , 31.5,
       29. , 16.7, 29.1, 20. , 19.3, 13.1, 20.2, 36.2, 24.7, 20.1, 13.9,
       14.1, 10.5,  7.4, 28.4, 30.8, 19. , 13.6, 21.9, 14.3, 26.6, 24.3,
       27.1, 23.8, 22. , 21.9, 13.3, 25. , 18.8, 34.7, 24.3, 25.1, 15.4,
       20.5, 20.4, 11.3, 20.1, 21.2, 16.5, 34.9, 21.2,  6.3, 23.1, 23.3,
       17.8, 10.9, 25. , 21.6, 23. , 23.1, 50. , 32.2, 14.5, 18.2,  7. ,
       13.1, 29. ,  8.3, 24.1, 24.8, 43.5, 33.2, 16.1, 22.4, 20.8, 27.9,
       23.6, 29.4, 15. , 13.1, 15.6, 20.6, 21.7, 14

In [11]:
y_train.shape

(379,)

In [12]:
y_test

array([19.5, 22.8, 36.5, 20.1, 24.6, 23.4, 41.7, 11.8,  8.5, 44. , 14.4,
       23. , 15.2, 38.7, 24.3, 13.4, 23.3, 23.8, 50. , 18.6, 29.8,  8.8,
       42.3, 14.1, 21.2, 19.2, 25.3, 22. , 43.8,  7.2, 30.7, 28.2, 22.1,
       21.5, 35.1, 24.4, 18.2, 23.4, 19.4, 17.3, 15.2, 19.3, 32.5, 21.7,
       17.1, 15.6, 28.1, 13.8, 15.2, 17.2,  8.8, 23.9, 36.1, 45.4, 13.5,
       20. , 14.6, 35.2, 22.3, 17.5, 20.6, 17.8, 18.5, 20.7, 24. , 14. ,
       23.8, 20.6, 27.5, 19.9, 23.3, 19.6, 11.5, 18.2, 14.3,  8.7, 24.8,
       22.3, 24.5, 28.7, 20.9, 17.1, 16.7, 13.4, 17. , 33.8, 30.1, 13.1,
       15.6, 16.6, 16. , 33.2,  8.3, 25. , 19.3, 31.6, 19.3, 19.4, 23. ,
       23.1, 21.8, 25. , 20.4, 12.3, 27.1, 20.8, 18.9, 10.8, 23.9, 21.2,
       19.5, 18.7, 44.8, 36. , 19.6, 41.3, 18.8, 11. , 18.5, 21.7, 37.2,
       19.8, 23.1, 19.2, 19.6, 11.7, 12.1])

In [13]:
y_test.shape

(127,)

Scaling function use for a purpose to scale data in manner form in which all values come to the same scale,because of its working this algorithm react faster to help the model for the accurate result

In [14]:
x_scalar=StandardScaler()
y_scalar=StandardScaler()

Here,we have to reshape the dependent data (y_train,y_test) in vector form for the standardscalar() function because it cannot scale the values in array form,so we have to change it and independent data (x_train,x_test) is already in vector form 

In [15]:
x_train=x_scalar.fit_transform(x_train)
y_train=y_scalar.fit_transform(y_train.reshape(379,1))

x_test=x_scalar.transform(x_test)
y_test=y_scalar.transform(y_test.reshape(127,1))

In [16]:
y_train

array([[-0.29483505],
       [ 0.5611832 ],
       [ 1.36370031],
       [ 0.0261718 ],
       [-0.49813938],
       [-0.80844599],
       [-0.42323778],
       [-0.53024006],
       [-0.94754896],
       [-0.99034987],
       [-1.51466105],
       [-0.54094029],
       [ 0.15457454],
       [-0.13433162],
       [ 0.68958594],
       [-0.40183733],
       [ 0.95709164],
       [ 2.92593362],
       [-0.01662911],
       [ 0.43278047],
       [ 2.92593362],
       [-0.93684873],
       [-1.33275717],
       [-1.16155352],
       [-0.00592889],
       [-0.02732934],
       [-0.45533847],
       [ 1.27809849],
       [ 2.92593362],
       [-0.01662911],
       [-0.50883961],
       [-0.82984645],
       [ 0.13317408],
       [ 1.14969575],
       [-0.28413482],
       [-0.18783276],
       [-0.0487298 ],
       [ 2.79753088],
       [-0.32693573],
       [-0.44463824],
       [ 2.74402974],
       [-0.90474805],
       [ 0.94639142],
       [-1.88916903],
       [-1.33275717],
       [ 0

In [17]:
y_test

array([[-0.33763596],
       [ 0.01547157],
       [ 1.48140282],
       [-0.27343459],
       [ 0.20807568],
       [ 0.07967294],
       [ 2.03781468],
       [-1.16155352],
       [-1.51466105],
       [ 2.28391993],
       [-0.88334759],
       [ 0.03687203],
       [-0.79774577],
       [ 1.71680784],
       [ 0.17597499],
       [-0.99034987],
       [ 0.06897271],
       [ 0.12247385],
       [ 2.92593362],
       [-0.43393801],
       [ 0.76448754],
       [-1.48256037],
       [ 2.10201605],
       [-0.91544828],
       [-0.15573208],
       [-0.36973664],
       [ 0.28297727],
       [-0.07013025],
       [ 2.26251947],
       [-1.65376402],
       [ 0.86078959],
       [ 0.59328389],
       [-0.05943003],
       [-0.1236314 ],
       [ 1.33159963],
       [ 0.18667522],
       [-0.47673892],
       [ 0.07967294],
       [-0.34833619],
       [-0.57304098],
       [-0.79774577],
       [-0.35903641],
       [ 1.0533937 ],
       [-0.10223094],
       [-0.59444143],
       [-0

SGD stands for Stochastic Gradiant Descent which is efficient model to predict the accracy of data

In [18]:
model=SGDRegressor(loss='squared_loss')

In [19]:
model.fit(x_train,y_train)

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:165: FutureWarning: The loss 'squared_loss' was deprecated in v1.0 and will be removed in version 1.2. Use `loss='squared_error'` which is equivalent.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor(loss='squared_loss')

In [20]:
prediction=model.predict(x_test)


In [24]:
scores=cross_val_score(model,x_test,y_test)


C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:165: FutureWarning: The loss 'squared_loss' was deprecated in v1.0 and will be removed in version 1.2. Use `loss='squared_error'` which is equivalent.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:165: FutureWarning: The loss 'squared_loss' was deprecated in v1.0 and will be removed in version 1.2. Use `loss='squared_error'` which is equivalent.
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using rave

In [25]:
scores

array([0.86616459, 0.78242829, 0.85083002, 0.79470928, 0.85559622])

In [26]:
print('Average Cross Validation: ',np.mean(scores))

Average Cross Validation:  0.8299456780715179
